version: "3"
services:
  devspace:
    build: .
    volumes:
      - ../:/workspace
    networks:
      - myproject
    depends_on:
      - redis
  redis:
    image: redis
    networks:
      - myproject
networks:
  myproject:
